export const ActionTypes = {
    SET_THEME: "SET_THEME",
    SET_ENTITY: "SET_ENTITY",
    SET_TICKETS:"SET_TICKETS",
    SET_DATE_RANGE:"SET_DATE_RANGE",
    SET_STATUS_COUNT:"SET_STATUS_COUNT",
    SET_TICKET_FLAG:"SET_TICKET_FLAG",
    SET_UNASSIGN_FLAG:"SET_UNASSIGN_FLAG",
    SET_TILE_FLAG:"SET_TILE_FLAG",
    SET_CANVAS_FLAG:"SET_CANVAS_FLAG",
    SET_TOOGLE_NOTIFICATION: "SET_TOOGLE_NOTIFICATION"
}